// Generated by CoffeeScript 1.8.0
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  angular.module('resto.commandeControllers', ['ui.bootstrap']).controller('CommandeController', function($scope, $http, $routeParams, Profile, Resto, Commande) {
    var param, update_total;
    $scope.form = {};
    param = $routeParams.param;
    $scope.order = {
      'details': {
        'commande': [],
        'addressTo': '',
        'addressFrom': '',
        'requestedTime': new Date()
      },
      'resto': param
    };
    Resto.query().$promise.then(function(value) {
      var resto;
      $scope.current_resto = ((function() {
        var _i, _len, _results;
        _results = [];
        for (resto = _i = 0, _len = value.length; _i < _len; resto = ++_i) {
          resto = value[resto];
          if (resto.pk === param) {
            _results.push(resto);
          }
        }
        return _results;
      })())[0];
      return $scope.order.details.addressFrom = $scope.current_resto.address;
    });
    $scope.add_item = function(item) {
      if (!$scope.profile) {
        return alert("Veuillez d'abord vous connecter");
      }
      if (!$scope.order.details.addressTo) {
        $scope.order.details.addressTo = $scope.profile.adresse[0];
      }
      if ($scope.sending) {
        $scope.order.details.commande = [];
      }
      $scope.sending = false;
      $scope.confirm = null;
      if (__indexOf.call($scope.order.details.commande, item) >= 0) {
        item.qty += 1;
      } else {
        item.qty = 1;
        $scope.order.details.commande.push(item);
      }
      return update_total();
    };
    $scope.remove_item = function(item) {
      $scope.order.details.commande = _.without($scope.order.details.commande, item);
      return update_total();
    };
    $scope.qty_adjust = function(item, adjustment) {
      item.qty = Math.max(1, item.qty + adjustment);
      return update_total();
    };
    update_total = function() {
      var item, _i, _len, _ref, _results;
      $scope.total = 0;
      _ref = $scope.order.details.commande;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        _results.push($scope.total += item.price * item.qty);
      }
      return _results;
    };
    $scope.place_order = function() {
      $scope.sending = true;
      if ($scope.order.details.addressTo === '##new') {
        $scope.profile.adresse.unshift($scope.new_address);
        $scope.order.details.addressTo = $scope.new_address;
        Profile.update({
          id: $scope.profile.user.pk
        }, $scope.profile);
      }
      return Commande.save($scope.order).$promise.then(function(value) {
        return $scope.confirm = value;
      });
    };
    $scope.minDate = new Date();
    $scope.hstep = 1;
    $scope.mstep = 15;
    return $scope.open = function($event) {
      $event.preventDefault();
      $event.stopPropagation();
      return $scope.opened = true;
    };
  }).controller('CommandeManageController', function($scope, $http, $location, $routeParams, Commande) {
    var directionsDisplay, directionsService, get_route, param;
    param = $routeParams.param;
    $scope.filtered = function(array, filter) {
      var name;
      return (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = array.length; _i < _len; _i++) {
          name = array[_i];
          if (filter.indexOf(name.status) !== -1) {
            _results.push(name);
          }
        }
        return _results;
      })();
    };
    if ($location.path() === '/deliver_commande') {
      directionsService = new google.maps.DirectionsService();
      directionsDisplay = new google.maps.DirectionsRenderer();
      get_route = function() {
        var map, request;
        request = {
          origin: $scope.current_location || $scope.selected_commande.details.addressFrom,
          waypoints: [
            {
              location: $scope.selected_commande.details.addressFrom,
              stopover: true
            }
          ],
          destination: $scope.selected_commande.details.addressTo,
          travelMode: google.maps.TravelMode.DRIVING
        };
        directionsService.route(request, function(response, status) {
          if (status === google.maps.DirectionsStatus.OK) {
            return directionsDisplay.setDirections(response);
          }
        });
        map = new google.maps.Map(document.getElementById('map-canvas'));
        return directionsDisplay.setMap(map);
      };
      $scope.set_selected = function(commande) {
        $scope.selected_commande = commande;
        if ($scope.selected_commande) {
          return get_route();
        }
      };
    }
    $scope.commandes = Commande.query({
      resto: param
    });
    return $scope.update_status = function(commande, status) {
      var updated_commande;
      updated_commande = commande;
      updated_commande.status = status;
      if (status = 'delivered') {
        updated_commande.details.deliveryTime = new Date();
      }
      return Commande.update({
        id: commande.pk
      }, updated_commande).$promise.then(function(value) {
        if (__indexOf.call(_.keys(value), 'error') >= 0) {
          return alert('Un autre livreur a déjà livré cette commande');
        } else {
          return commande = value;
        }
      });
    };
  }).controller('CommandeConfirmController', function($scope, $http, $routeParams, Commande) {
    var param;
    param = $routeParams.param;
    $scope.total = 0;
    return Commande.get({
      id: param
    }).$promise.then(function(value) {
      var item, _i, _len, _ref;
      _ref = value.details.commande;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        $scope.total += item.price * item.qty;
      }
      if (value.status === 'pending') {
        value.status = 'paid';
        Commande.update({
          id: param
        }, value);
      }
      return $scope.confirm = value;
    });
  });

}).call(this);
