// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('resto.homeControllers', []).controller('HomeController', function($scope, $http) {
    $scope.restos = [];
    return $http.get('http://127.0.0.1:8000/api/resto').success(function(data) {
      return $scope.restos = data;
    });
  });

}).call(this);
