// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('resto.services', ['ngResource']).factory('Resto', function($resource) {
    return $resource('http://127.0.0.1:8000/api/resto/:id', {
      id: '@_id'
    }, {
      update: {
        method: 'PUT'
      }
    });
  }).factory('Profile', function($resource) {
    return $resource('http://127.0.0.1:8000/api/profile/:id', {
      id: '@_id'
    }, {
      update: {
        method: 'PUT'
      }
    });
  }).factory('Commande', function($resource) {
    return $resource('http://127.0.0.1:8000/api/commande/:id', {
      id: '@_id'
    }, {
      update: {
        method: 'PUT'
      }
    });
  });

}).call(this);
