// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('resto.prod', []).constant('conf', {
    url: 'http://ram.mdupuis.com/api/'
  });

  angular.module('resto.dev', []).constant('conf', {
    url: 'http://127.0.0.1:8000/api/'
  });

  angular.module('resto.services', ['ngResource', 'resto.dev']).factory('Resto', function($resource, conf) {
    return $resource(conf.url + 'resto/:id', {
      id: '@_id'
    }, {
      update: {
        method: 'PUT'
      }
    });
  }).factory('Profile', function($resource, conf) {
    return $resource(conf.url + 'profile/:id', {
      id: '@_id'
    }, {
      update: {
        method: 'PUT'
      }
    });
  }).factory('Commande', function($resource, conf) {
    return $resource(conf.url + 'commande/:id', {
      id: '@_id'
    }, {
      update: {
        method: 'PUT'
      }
    });
  });

}).call(this);
